### ISSUE TITLE
Empty entities packages

### ISSUE THREAD

**Issue by rabacadabra** [ebaloaloa/lick-hunter-server#135]
**Describe the bug**
`com.lickhunter.web.entities` package doesn't have the table defs, eg: com.lickhunter.web.entities.tables.records.SymbolRecord

**To Reproduce**
Steps to reproduce the behaviour:
1. Clone the repository and try to build

**Expected behaviour**
The package should contain database table definitions

**Screenshots**
![image](https://user-images.githubusercontent.com/52073446/145685744-a02b5daa-8d2f-4938-b116-dc25c1815c55.png)

IDE : IntelliJ IDEA

**Comment by ebaloaloa** [comment]
This is auto-generated
