### ISSUE TITLE
Feature Request: Soft Stop

### ISSUE THREAD

**Issue by jdv-21** [ebaloaloa/lick-hunter-server#51]
**Is your feature request related to a problem? Please describe.**
Currently we can use scheduler.lickhunter to schedule hourly restarts. We are running the bot on a specific schedule to hopefully avoid the volume during other hours. The problem is that sometimes when we're on our last hour of running, the bot would be stuck in a position or two. What happens is that the `Stop Profit` and `Stop Websocket` scripts would be triggered at the end of the day but this would also mean that the bot would no longer be able to buy positions (not open new ones) as it's already stopped.

**Describe the solution you'd like**
What would be ideal is to implement a way to stop the bot or trigger a "_soft stop_" where the bot would stop getting new open positions, work on the current opened ones and wait until it closes until the bot comes to a stop.

**Ways to implement:**
- Perhaps we can add a "_soft-stop_" feature where instead of pausing the bot right away, it'll do the above. This could function the same way as the `Stop Profit` and `Stop Websocket` where we could call the script on our last hour of run time but would wait until the last position is closed before shutting down. This is for added protection.
- Another way is to be able to switch over to a different set of settings on a scheduled time. This way we could use 0 for `maxOpen` so that the bot would stop taking new trades at a certain schedule. However, even if the bot stops taking new positions, if it is already stuck on an opened position that will continue to get stuck, that would still be problematic - it should wait for that position to get closed first before shutting down. Perhaps, we could add a toggle for "_soft-stop_" in the settings so the bot would stop taking new positions, work on the current ones and stop after they're closed.

**Comment by ebaloaloa** [comment]
Added pause feature on previous release. Bot will pause after all positions are closed.
