### ISSUE TITLE
Feature Request: autoInclude

### ISSUE THREAD

**Issue by jdv-21** [ebaloaloa/lick-hunter-server#58]
@ebaloaloa was able to implement a very much needed feature: AutoExclude during the 0.4.0 release 
```
"autoExclude" : true,
"autoExcludePercentage" : 70
```

This `autoInclude` feature functions in a similar way but instead of appending it to the exclusion list in the query.json file, it removes it.

**Is your feature request related to a problem? Please describe.**
I am currently using the `autoExclude` feature which was introduced back in the 0.4.0 release to automatically exclude coins that have exceeded a certain value within the past 24 hours. This value is around 20% to avoid fluctuations and for safety reasons. However, % changes in these coins can somehow be very volatile. One minute it's up 20%, next few hours it's already down 10% and so on. While having a low value for autoExclude works well for me, I keep finding myself deleting the coins every day to _refresh_ the  list of coins so it doesn't exclude the ones that are no longer above 20%. Sometimes I end up with over 60 excluded coins due to my low threshold.

**Describe the solution you'd like**
Similarly to the `autoExclude` feature, it would be great to have an autoInclude feature that would check the coins, determine if it has stabilized already and remove it from the exclusion list.

**Ways to implement:**
Correct me if I'm wrong or missing something here but I believe a similar approach to the 0.4.0 update would do the trick.
```
"autoInclude : true/false,
"autoIncludePercentage" : X
"autoIncludeInterval" : X
```

`autoInclude`: A toggle to enable/disable the feature. 
`autoIncludePercentage`: The value to check before removing it from the exclusion list
`autoIncludeInterval`: The only new one among the 3. The purpose of this is to give it enough time before checking again and determining if the coin should be removed from the list. This is to avoid fluctuations and so that the coins wouldn't be excluded and then included every few seconds.

**Comment by ebaloaloa** [comment]
@jdv-21 Have you tried using "maxPriceChangePercent"  in query.json? You can set maximum allowable percentage change from past 24H. I think this will work with your strategy to filter coins.

**Comment by jdv-21** [comment]
You're right. Thanks!
