### ISSUE TITLE
Bot Status

### ISSUE THREAD

**Issue by wormsound** [ebaloaloa/lick-hunter-server#62]
**Is your feature request related to a problem? Please describe.**
There is no way to check if the bot is active or pause state. Also, we cannot know which setting is activated.

**Describe the solution you'd like**
Add telegram command for checking bot status Ex. /status 
Result looks like this:
Status: [Acitve/Pause]
Settings: [settings1]
Schedule: [Enable/Disable]
Profit: [Started/Stopped]
Websocket: Profit: [Started/Stopped]

**Comment by ebaloaloa** [comment]
This will be included in next release.
